# Generated by Django 5.2.4 on 2025-08-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="created_at",
            new_name="timestamp",
        ),
    ]
