# Generated by Django 5.2.5 on 2025-08-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_membershipplan_usermembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greeting_message",
                    models.TextField(default="Hello! How can I help you today?"),
                ),
                (
                    "fallback_reply",
                    models.TextField(
                        default="I'm sorry, I don't understand. Can you please rephrase?"
                    ),
                ),
                ("max_conversation_history", models.IntegerField(default=10)),
                ("confidence_threshold", models.FloatField(default=0.8)),
            ],
        ),
    ]
