# Generated by Django 5.2.5 on 2025-08-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_botsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="max_conversation_history",
            field=models.IntegerField(default=10),
        ),
    ]
