# Generated by Django 5.2.5 on 2025-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_chatsession_max_conversation_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="response_time",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
